export const ADD_PROFILE_DOCUMENT = 'ADD_PROFILE_DOCUMENT';
export const UPDATE_NEW_DOCUMENT = 'UPDATE_NEW_DOCUMENT';
export const SUBMIT_ANALYSIS = 'SUBMIT_ANALYSIS';
export const ANALYSIS_SUCCESS = 'ANALYSIS_SUCCESS';
export const ANALYSIS_FAILURE = 'ANALYSIS_FAILURE';
export const CLEAR_ANALYSIS = 'CLEAR_ANALYSIS';
export const TOGGLE_SENTENCE_LEVEL_ANALYSIS = 'TOGGLE_SENTENCE_LEVEL_ANALYSIS';
export const ANALYSIS_REDUCER = 'analysisReducer';
